name: "wiki.mbirth.de"
description: "All you never wanted to know"

url: "http://wiki.mbirth.de"

permalink: none

paginate: 20

markdown: kramdown
#markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md
#permalink: pretty

# TODO: using rouge via kramdown when GitHub supports it
highlighter: pygments

safe: true
lsi: false

encoding: "utf-8"
timezone: "Europe/Berlin"

github:
    project_title: "Wiki"
    project_tagline: "Experimental Wiki with Jekyll"

gems:
    - jemoji
    - jekyll-sitemap

redcarpet:
    extensions: ["autolink", "tables", "no_intra_emphasis"]

kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

defaults:
    -
        scope:
            path: ""   # an empty string here means all files in the project
            type: "posts"  # "post" for Jekyll <=2.2
        values:
            language: en

