name: "wiki.mbirth.de"
description: "All you never wanted to know"

url: "http://wiki.mbirth.de"

#paginate: 10

markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md
#permalink: pretty
highlighter: pygments

safe: true
lsi: false

github:
    project_title: "Wiki"
    project_tagline: "Experimental Wiki with Jekyll"

gems:
    - jemoji

redcarpet:
    extensions: ["autolink", "tables"]
