name: "wiki.mbirth.de"
description: "All you never wanted to know"

url: "http://wiki.mbirth.de"

permalink: none

paginate: 20

markdown: kramdown
#markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md
#permalink: pretty

# This is for {% highlight %} blocks
highlighter: rouge

safe: true
lsi: false

encoding: "utf-8"
timezone: "Europe/Berlin"

github:
    project_title: "Wiki"
    project_tagline: "Experimental Wiki with Jekyll"

gems:
    - kramdown
    - jemoji
    - jekyll-sitemap
    - jekyll-redirect-from

redcarpet:
    extensions: ["autolink", "tables", "no_intra_emphasis"]

kramdown:
    input: GFM
    hard_wrap: false
    # This is for fenced code blocks: ~~~
    syntax_highlighter: rouge

defaults:
    -
        scope:
            path: ""   # an empty string here means all files in the project
            type: "posts"  # "post" for Jekyll <=2.2
        values:
            language: en

